apiVersion: apps/v1
kind: Deployment
metadata:
  name: qtud-sso
  namespace: c04
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qtud-sso
  template:
    metadata:
      labels:
        app: qtud-sso
    spec:
      volumes:
        - name: logs
          emptyDir: { }
        - name: promtail-config
          configMap:
            name: promtail-config
      containers:
        - name: qtud-sso
          image: registry.gtelsoft.vn/c04/qtud:1.1
          ports:
            - containerPort: 9000
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: logs
              mountPath: /app/logs
        - name: promtail
          image: grafana/promtail:2.9.3
          args:
            - -config.file=/etc/promtail/config.yaml
          volumeMounts:
            - name: logs
              mountPath: /app/logs
            - name: promtail-config
              mountPath: /etc/promtail
          env:
            - name: PROJECT_NAME
              value: c04-qtud
            - name: SERVICE_NAME
              value: qtud-sso
      restartPolicy: Always
      imagePullSecrets:
        - name: docker-registry