spring:
  application:
    name: product-sv
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://192.168.5.51:8761/eureka}
  instance:
    preferIpAddress: true
